use chrono::Utc;

use crate::types::*;

pub fn seed_market() -> MarketSnapshot {
    MarketSnapshot {
        market_id: "mythiv-local-market".to_string(),
        quote_currency: "COMPUTE_CREDIT".to_string(),
        generated_at: Utc::now(),
        current_tick: 0,
        whitelist_enabled: false,
        whitelisted_trader_count: 0,
        node_count: 0,
        job_count: 0,
        quote_count: 0,
        fill_count: 0,
        settlement_total: 0.0,
        policy: BrainPolicy {
            mode: "asimog-private-market-policy".to_string(),
            private_bias: 0.10,
            urgency_multiplier_high: 1.35,
            urgency_multiplier_normal: 1.00,
            urgency_multiplier_low: 0.92,
            reliability_weight: 0.55,
        },
        asimog: AsimogProfile {
            name: "AsiMOG".to_string(),
            private_brain_role: "Private superbrain for routing, reserve policy, trust policy, and backend governance.".to_string(),
            public_brain_role: "Public market narrator for summaries, commentary, public quotes, and X-facing communications.".to_string(),
            backend_role: "Runs market intelligence, backend orchestration, policy enforcement, and settlement preparation.".to_string(),
            market_charter: "Protect the market first. Price compute honestly. Route sensitive work to private trust surfaces. Keep the public story legible.".to_string(),
        },
        clawmog: ClawmogProfile {
            name: "ClawMOG".to_string(),
            frontend_role: "Builds the web GUI, operator shell, forms, surfaces, and market visibility layer.".to_string(),
            operator_shell_role: "Maintains TUI and web control surfaces for humans and approved operators.".to_string(),
            public_surface_role: "Translates market state into legible panels, logs, and public-facing interfaces.".to_string(),
        },
        whitelist: None,
        nodes: vec![
            ComputeNode {
                id: "node-alpha".to_string(),
                operator_address: "9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb4g7TgKqX".to_string(),
                role: NodeRole::Builder,
                available_minutes: 180,
                price_floor_per_minute: 0.28,
                reliability: 0.97,
                trust: TrustLevel::Private,
            },
            ComputeNode {
                id: "node-beta".to_string(),
                operator_address: "ComputeNodePublic1111111111111111111111111111".to_string(),
                role: NodeRole::Solver,
                available_minutes: 240,
                price_floor_per_minute: 0.22,
                reliability: 0.91,
                trust: TrustLevel::Public,
            },
            ComputeNode {
                id: "node-gamma".to_string(),
                operator_address: "ResearchNodePrivate11111111111111111111111111".to_string(),
                role: NodeRole::Research,
                available_minutes: 140,
                price_floor_per_minute: 0.31,
                reliability: 0.94,
                trust: TrustLevel::Private,
            },
            ComputeNode {
                id: "node-delta".to_string(),
                operator_address: "RenderNodePublic11111111111111111111111111111".to_string(),
                role: NodeRole::Render,
                available_minutes: 320,
                price_floor_per_minute: 0.19,
                reliability: 0.88,
                trust: TrustLevel::Public,
            },
        ],
        jobs: vec![
            ComputeJob {
                id: "job-001".to_string(),
                owner: "agent-mesh".to_string(),
                owner_address: "TraderAlpha111111111111111111111111111111111".to_string(),
                desired_role: NodeRole::Builder,
                requested_minutes: 45,
                max_budget: 18.0,
                urgency: Urgency::High,
                required_trust: TrustLevel::Private,
            },
            ComputeJob {
                id: "job-002".to_string(),
                owner: "world-directory".to_string(),
                owner_address: "TraderBeta1111111111111111111111111111111111".to_string(),
                desired_role: NodeRole::Research,
                requested_minutes: 30,
                max_budget: 12.0,
                urgency: Urgency::Normal,
                required_trust: TrustLevel::Private,
            },
            ComputeJob {
                id: "job-003".to_string(),
                owner: "hashmedia".to_string(),
                owner_address: "TraderGamma111111111111111111111111111111111".to_string(),
                desired_role: NodeRole::Render,
                requested_minutes: 60,
                max_budget: 16.0,
                urgency: Urgency::Low,
                required_trust: TrustLevel::Public,
            },
        ],
        quotes: vec![],
        fills: vec![],
        settlements: vec![],
        events: vec![
            MarketEvent {
                at: Utc::now(),
                kind: EventKind::PolicyApplied,
                message: "AsiMOG market policy seeded. ClawMOG operator surfaces standing by.".to_string(),
            },
        ],
    }
}
